# Generated by Django 3.2.5 on 2022-05-01 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainRunner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpus', models.CharField(max_length=20)),
                ('pid', models.IntegerField()),
                ('port', models.IntegerField()),
                ('config', models.CharField(max_length=200)),
                ('log_dir', models.CharField(max_length=200)),
                ('cache_file', models.CharField(max_length=200)),
                ('resume_from', models.CharField(max_length=200)),
                ('load_from', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestRunner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpus', models.CharField(max_length=20)),
                ('pid', models.IntegerField()),
                ('port', models.IntegerField()),
                ('config', models.CharField(max_length=200)),
                ('log_dir', models.CharField(max_length=200)),
                ('cache_file', models.CharField(max_length=200)),
                ('weight', models.CharField(max_length=200)),
                ('aug_test', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
