# Generated by Django 3.2.5 on 2022-05-01 10:04

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_path', models.CharField(max_length=256)),
                ('text_content', mdeditor.fields.MDTextField()),
            ],
        ),
        migrations.CreateModel(
            name='FileList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('record', 'record'), ('config', 'config'), ('code', 'code'), ('data', 'data')], max_length=16)),
                ('origin_dir', models.CharField(max_length=256)),
                ('current_dir', models.CharField(max_length=256)),
                ('current_file', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user')),
            ],
        ),
    ]
